### ISSUE TITLE
Q/A Checklist - Release 1.3

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion-saltstack#460]
### Release Changelog
Responsible: 

_Notes:_ 
- [ ] Confirm that all changes have been documented in changes.json and it displays correctly in SOC

***

### User Management
Responsible: 

_Notes:_ 
- [x] Post-install, use `so-user` to add a user and login to web-ui with it
- [x] Logout from the web-ui, and use `so-user` to change the user password and log back in with the new password (bug filed regarding Kibana/Navigator interaction)

***

### BPF Functionality
Responsible: @defensivedepth 

_Notes: Test on both Ubuntu network install & Centos ISO_
- [ ] Edit /opt/so/salt/pillar/static.sls with the values from [these](https://github.com/Security-Onion-Solutions/securityonion-saltstack/wiki/BPF#pillar-bpf-syntax) docs; Highstate the system and confirm no errors.
- [ ] Edit /opt/so/salt/pillar/minions/<hostname>.sls with different values; Highstate the system confirm that the bpf was overridden and applied successfully.

***

### Network Datasets - Basic Functionality
Responsible:  @dougburks 

_Notes:_ 

#### EVAL Install:
- [ ] Run `so-tcpreplay` & confirm traffic is replayed to `bond0`
- [x] Login to Kibana & confirm that Zeek data has been generated and is viewable
- [x] Login to TheHive & confirm that NIDS alerts have been generated and that you can pivot to the NIDS Dashboard
- [ ] View a network event in Kibana:
   - [x] Pivot to the Indicator dashboard
   - [x] Pivot to a Sensoroni transcript
   - [ ] Use the `Add2Hive` link to create a TheHive alert from the event

#### Distributed Install (Master + Forward):

***

### Host Datasets - Osquery
Responsible:  

_Notes:_ 

#### EVAL Install:
- [ ] Select `Fleet` during setup
- [ ] Post-install, login to Fleet & confirm that the EVAL system is enrolled
- [ ] Run the following query against the EVAL system:
    - [ ] `select * from osquery_info`
    - [ ] Confirm that the osquery version is >= 4.2
- [ ] Open Kibana and confirm that osquery data shows up in the relevant dashboards

***

### Host Datasets - Wazuh
Responsible:  

_Notes:_ 

#### EVAL Install:
- [ ] TBD

***

### Host Datasets - Winlogbeat/Sysmon
Responsible:  

_Notes:_ 

#### EVAL Install:
- [ ] TBD

***

### Playbook

Responsible: @defensivedepth 

_Notes: Login as analyst_

- [x] Load sample play in Sigma Editor
- [x] Click `Convert` & confirm the corresponding elasticsearch query appears in the righthand box
- [x] Click `Create Play` and confirm that a Play is created
