### ISSUE TITLE
SO integration test checklist

### ISSUE THREAD

**Issue by rwwiv** [Security-Onion-Solutions/securityonion-saltstack#750]
* SOC
  * Overview
    - [x] content matches changes.json file
    - [x] number of items in list is correct
    - [x] correct title
  * Hunt
    - [x] number of dropdown items matches expected value
    - [x] correct order of dropdown items
    - [x] query shows in recent queries after clicking hunt
    - [x] fifo (last 5) functions as intended in recent queries
    - [x] relative > absolute time is correct
    - [x] correct sections show based on query terms
    - [x] clicking a query from the dropdown runs that query
    - [x] clicking (+)/(-) on field includes/excludes that field from the query
    - [x] clicking pcap link creates pcap job
    - [x] changing each [rows per page] value is reflected in ui
    - [x] changing each [fetch limit] value is reflected in ui
    - [x] clicking the arrow on an event shows/hides all information
    - [x] sort columns works correctly
    - [x] timeframe is correct
    - [x] pcap link creates job with correct parameters
    - [x] groupby button in event details add field to grouby
    - [x] hunt query reflected in browser title
    - [x] auto-hunt checkbox works
  * PCAP
    - [x] pcap dialog appears when clicking (+) button
    - [x] pcap job appears in list with correct info after adding job
    - [x] pcap with correct values will eventually move from pending to complete
    - [x] clicking binoculars/job id shows pcap ui
    - [x] collapse/expand all works
    - [x] changing rows per page works
    - [x] unwrap flag is set on download link
    - [x] sort columns works correctly
    - [x] show only application data filters correctly
    - [x] hex shows/hides as expected
    - [x] download link shows correct job id
  * Tools
    - [x] number of external tools in sidebar is correct
    - [x] names of items in list are correct
  * Downloads
    - [x] packages list exists and has correct items + number of items
    - [x] configs list exists and has correct items + number of item
    - [x] links have correct relative URLs
    - [x] loggers section has currect URLs
  * Administration
    - Users
      - [x] table contains onionuser entry
      - [ ] (Future) can edit First Name + Last Name
  * Profile Settings
    - [x] Change Password
* Kibana
  - [x] Log count is not 0
  - [x] Push to TheHive creates alert
  - [x] clicking job id creates pcap job in SOC
  - [x] all dashboards loaded
* Grafana
  - [ ] dashboard exists (not implemented for standalone yet)
* Playbook
  - [x] expected number of plays imported
  - [x] valid links on sigma editor page
  - [x] sigma editor creates ES query correctly
  - [x] sigma editor creates play with information from sigma yaml
  - [x] when play is set to active, thehive should have a case template created with play id as name
